# Generated by Django 5.0.7 on 2024-10-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='temporary_secret_key',
            field=models.CharField(blank=True, help_text='A temporary secret key for verification purposes.', max_length=36, null=True),
        ),
    ]
